/*
 * Copyright (c) 2008-2016 Computer Network Information Center (CNIC), Chinese Academy of Sciences.
 * 
 * This file is part of Duckling project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 *
 */
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.duckling.ddl.web.controller;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.duckling.ddl.web.interceptor.access.RequirePermission;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;


/**
 * 滚动图片效果
 * @date May 12, 2011
 * @author diyanliang@cnic.cn
 */
@Controller
@RequestMapping("/{teamCode}/imgScrService")
@RequirePermission(target="team", operation="view")
public class ImgScrServiceController extends BaseController {
	@RequestMapping
	public ModelAndView execute(HttpServletRequest request, HttpServletResponse response) {
		String strpathes=request.getParameter("path");
		String[] pathes=strpathes.split("\\|");
		StringBuffer str=new StringBuffer();
		for(String strarr:pathes){
			String[] arr=strarr.split(":");
			String id=arr[0];
			str.append("var "+id+"=[");
			str.append("];\n");
			
		}
		response.setContentType("text;charset=UTF-8");
		try {
		    Writer wr = response.getWriter();
		    wr.write(str.toString());
		    wr.close();
		} catch (IOException e) {
			LOGGER.error("",e);
		}
		return null;
	}

	@RequestMapping(params="func='open")
	public ModelAndView opendialog(HttpServletRequest request) {
		ArrayList<String> results=new ArrayList<String>();
		request.setAttribute("results", results);
		return new ModelAndView("fck_imagescroll.jsp");
	}
   
}