--
-- for Derby <2022-03-03 Thu>
--

CREATE TABLE a1_browse_log (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  rid int DEFAULT NULL,
  item_type varchar(10) DEFAULT NULL,
  user_id varchar(255) NOT NULL DEFAULT '',
  display_name varchar(255) DEFAULT NULL,
  tracking_id varchar(255) DEFAULT NULL,
  browse_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  PRIMARY KEY (id)
);
CREATE INDEX tracking_id ON a1_browse_log (tracking_id);
CREATE INDEX browse_log_index ON a1_browse_log (rid,browse_time);

CREATE TABLE a1_bundle (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  bid int NOT NULL DEFAULT 0,
  status varchar(25) DEFAULT NULL,
  tid int NOT NULL DEFAULT 0,
  title varchar(255) DEFAULT NULL,
  create_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  creator varchar(255) DEFAULT NULL,
  last_editor varchar(255) DEFAULT NULL,
  last_edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  last_version int NOT NULL DEFAULT 1,
  description clob,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX bundle_index ON a1_bundle (bid,tid);

CREATE TABLE a1_bundle_item (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  bid int NOT NULL,
  rid int NOT NULL,
  sequence int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX b_item_index ON a1_bundle_item (tid,bid);

CREATE TABLE a1_copy_log (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  from_version int DEFAULT NULL,
  from_rid int DEFAULT NULL,
  from_tid int DEFAULT NULL,
  to_version int DEFAULT NULL,
  to_rid int DEFAULT NULL,
  to_tid int DEFAULT NULL,
  copy_time timestamp DEFAULT NULL,
  uid varchar(255) DEFAULT NULL,
  ancestry_rid int DEFAULT 0,
  type varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE a1_device_token (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  device_token varchar(255) NOT NULL,
  last_login_time timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE a1_emailattach (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  rid int NOT NULL,
  item_type varchar(45) DEFAULT NULL,
  creator varchar(255) NOT NULL,
  mid varchar(128) NOT NULL,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX email_mid ON a1_emailattach (mid);
CREATE INDEX emailattach_tid_creator ON a1_emailattach (tid);

CREATE TABLE a1_file (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  clb_id int NOT NULL,
  status varchar(25) DEFAULT NULL,
  fid int NOT NULL DEFAULT 0,
  tid int NOT NULL DEFAULT 0,
  title varchar(255) DEFAULT NULL,
  create_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  creator varchar(255) DEFAULT NULL,
  last_editor varchar(255) DEFAULT NULL,
  last_edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  last_version int NOT NULL DEFAULT 1,
  clb_version int DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX file_index ON a1_file (fid,tid);

CREATE TABLE a1_file_version (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  rid int NOT NULL,
  tid int NOT NULL,
  version int NOT NULL DEFAULT 1,
  clb_id int NOT NULL,
  size bigint DEFAULT 0,
  title varchar(255) DEFAULT NULL,
  editor varchar(255) DEFAULT NULL,
  edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  status varchar(10) DEFAULT NULL,
  clb_version int DEFAULT NULL,
  checksum varchar(255) DEFAULT NULL,
  device varchar(300) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX file_version_index ON a1_file_version (tid,version);
CREATE INDEX file_rid_index ON a1_file_version (rid);

CREATE TABLE a1_grid_group (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  uid varchar(255) NOT NULL,
  last_edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  grid_map blob NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX grid_group_index ON a1_grid_group (tid,uid);

CREATE TABLE a1_mobile_version (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  type varchar(45) NOT NULL,
  version varchar(45) NOT NULL,
  creator varchar(45) NOT NULL,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description clob,
  PRIMARY KEY (id)
);

CREATE TABLE a1_navbar_item (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  tid int NOT NULL,
  title varchar(255) NOT NULL,
  url clob,
  sequence int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX navbar_index ON a1_navbar_item (uid,tid);

CREATE TABLE a1_page (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  pid int NOT NULL,
  tid int NOT NULL DEFAULT 0,
  status varchar(25) DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  create_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  creator varchar(255) DEFAULT NULL,
  creator_name varchar(255) DEFAULT NULL,
  last_editor varchar(255) DEFAULT NULL,
  last_editor_name varchar(255) DEFAULT NULL,
  last_edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  last_version int NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX page_index ON a1_page (pid,tid);

CREATE TABLE a1_page_version (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  rid int NOT NULL,
  version int NOT NULL DEFAULT 1,
  title varchar(255) DEFAULT NULL,
  editor varchar(255) DEFAULT NULL,
  edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  content clob,
  status varchar(10) DEFAULT NULL,
  size bigint DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE INDEX page_version_index ON a1_page_version (tid,version);
CREATE INDEX page_rid_index ON a1_page_version (rid);

CREATE TABLE a1_page_view (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  rid int NOT NULL DEFAULT 0,
  item_type varchar(10) DEFAULT NULL,
  user_id varchar(255) NOT NULL DEFAULT '',
  display_name varchar(255) DEFAULT NULL,
  browse_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  tracking_id varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX page_view_rid ON a1_page_view (rid);
CREATE INDEX page_view_tid ON a1_page_view (tid);

CREATE TABLE a1_pan_space_application (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(45) NOT NULL,
  application_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  application_type varchar(10) NOT NULL,
  approve_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  new_size bigint NOT NULL,
  original_size bigint NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX uid_tree_index ON a1_pan_space_application (uid);

CREATE TABLE a1_param (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  item_id varchar(50) DEFAULT NULL,
  "key" varchar(50) DEFAULT NULL,
  value varchar(50) DEFAULT NULL,
  type varchar(50) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE a1_picture (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  file_clb_version int DEFAULT NULL,
  file_clb_id int DEFAULT NULL,
  width int DEFAULT NULL,
  height int DEFAULT NULL,
  clb_id int DEFAULT NULL,
  create_time timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX picture_index ON a1_picture (file_clb_version,file_clb_id);

CREATE TABLE a1_resource (
  rid int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  item_type varchar(25) DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  creator varchar(255) DEFAULT NULL,
  create_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  last_editor varchar(255) DEFAULT NULL,
  last_editor_name varchar(255) DEFAULT NULL,
  last_edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  last_version int NOT NULL DEFAULT 1,
  tags clob NOT NULL,
  file_type varchar(255) DEFAULT NULL,
  marked_users blob NOT NULL,
  bid int NOT NULL,
  status varchar(10) NOT NULL,
  order_type int NOT NULL,
  description clob,
  size bigint DEFAULT 0,
  -- COMMENT '文件是否分享 0未分享 1已分享'
  shared int DEFAULT 0,
  PRIMARY KEY (rid)
);
CREATE INDEX resource_tid_bid_index ON a1_resource (tid,bid);

CREATE TABLE a1_search_docweight (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  keyword varchar(255) NOT NULL,
  rid int NOT NULL,
  weight int NOT NULL,
  time timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE a1_searchedlog (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  keyword varchar(255) NOT NULL,
  item_type varchar(255) DEFAULT NULL,
  item_id int DEFAULT 0,
  sequence int DEFAULT 0,
  opername varchar(255) DEFAULT NULL,
  time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  tid int NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE a1_searchlog (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  keyword varchar(255) NOT NULL,
  item_type varchar(255) DEFAULT NULL,
  item_id int DEFAULT 0,
  sequence int DEFAULT 0,
  opername varchar(255) DEFAULT NULL,
  time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  tid int NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE a1_shortcut (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  sequence int NOT NULL DEFAULT 0,
  tid int NOT NULL DEFAULT 0,
  tgid int NOT NULL,
  rid int NOT NULL,
  color varchar(45) DEFAULT NULL,
  creator varchar(45) DEFAULT NULL,
  createtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE a1_starmark (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  rid int NOT NULL,
  tid int NOT NULL,
  uid varchar(255) NOT NULL,
  create_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  PRIMARY KEY (id)
);
CREATE INDEX star_mark_index ON a1_starmark (tid,uid);

CREATE TABLE a1_tag (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  title varchar(255) DEFAULT NULL,
  creator varchar(255) DEFAULT NULL,
  count int NOT NULL DEFAULT 0,
  group_id int NOT NULL,
  create_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  pinyin varchar(255) DEFAULT NULL,
  sequence int DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE INDEX tag_index ON a1_tag (tid,group_id);

CREATE TABLE a1_tag_group (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  title varchar(255) DEFAULT NULL,
  creator varchar(255) DEFAULT NULL,
  sequence int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX tag_group_index ON a1_tag_group (tid);

CREATE TABLE a1_tag_item (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  tgid int NOT NULL,
  rid int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX tag_item_index ON a1_tag_item (tid,tgid);

CREATE TABLE a1_team_space_application (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  uid varchar(45) NOT NULL,
  application_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  application_type varchar(10) NOT NULL,
  approve_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  new_size bigint NOT NULL,
  original_size bigint NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX team_space_appl_tid_tree_index ON a1_team_space_application (tid);

CREATE TABLE a1_team_space_config (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid varchar(45) NOT NULL,
  size bigint NOT NULL,
  update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_uid varchar(45) NOT NULL,
  description clob,
  PRIMARY KEY (id)
);

CREATE TABLE a1_user_config (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(45) NOT NULL,
  max_create_team int NOT NULL,
  config_uid varchar(45) DEFAULT NULL,
  config_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description clob,
  PRIMARY KEY (id)
);

CREATE TABLE a1_user_copy_count (
  uid varchar(45) NOT NULL,
  copy_date varchar(20) NOT NULL,
  count varchar(45) NOT NULL,
  PRIMARY KEY (uid,copy_date)
);

CREATE TABLE a1_user_guide (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  module varchar(20) NOT NULL,
  step int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX user_guide_index ON a1_user_guide (uid);

CREATE TABLE a1_user_preferences (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  refresh_team_mode varchar(255) NOT NULL,
  default_team int NOT NULL,
  access_home_mode varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX user_pre_index ON a1_user_preferences (uid);

CREATE TABLE a1_user_sim (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  simuid varchar(255) NOT NULL,
  score int DEFAULT 0,
  time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  PRIMARY KEY (id)
);

CREATE TABLE a1_user_sort_preference (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(45) NOT NULL,
  type varchar(45) NOT NULL,
  sort_type varchar(45) NOT NULL,
  last_modify timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE a1_userinterest (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) NOT NULL,
  interest varchar(255) NOT NULL,
  score int DEFAULT 0,
  time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  PRIMARY KEY (id)
);

-- CREATE TABLE apn_user (
--   id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   created_date datetime DEFAULT NULL,
--   email varchar(64) DEFAULT NULL,
--   name varchar(64) DEFAULT NULL,
--   password varchar(64) DEFAULT NULL,
--   updated_date datetime DEFAULT NULL,
--   username varchar(64) NOT NULL,
--   PRIMARY KEY (id)
-- );
--   CREATE UNIQUE INDEX apn_username ON apn_user (username);

CREATE TABLE ddl_activity (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(255) DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  remark varchar(1000) DEFAULT NULL,
  begin_time timestamp DEFAULT NULL,
  end_time timestamp DEFAULT NULL,
  -- COMMENT '0新建,1进行中,2已结束'
  status int DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ddl_folder_path (
  tid int NOT NULL,
  rid int NOT NULL,
  ancestor_rid int NOT NULL,
  length int NOT NULL,
  PRIMARY KEY (tid,rid,ancestor_rid)
);
CREATE INDEX ancestor_rid_tid_index ON ddl_folder_path (tid,ancestor_rid);
CREATE INDEX rid_ancestorrid_index ON ddl_folder_path (rid,ancestor_rid);

CREATE TABLE ddl_item_mapping (
  tid int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  item_type varchar(45)  NOT NULL,
  item_id int NOT NULL,
  rid int NOT NULL,
  PRIMARY KEY (tid,item_type,item_id)
);

CREATE TABLE ddl_jounal (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int DEFAULT NULL,
  jid int DEFAULT NULL,
  device varchar(300) DEFAULT NULL,
  operation varchar(50) DEFAULT NULL,
  fid int DEFAULT NULL,
  fver int DEFAULT NULL,
  occur_time timestamp DEFAULT CURRENT_TIMESTAMP,
  is_dir boolean DEFAULT NULL,
  path varchar(2000) DEFAULT NULL,
  to_path varchar(2000) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX jid_index ON ddl_jounal (tid,jid);

-- CREATE TABLE ddl_lottery (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   user varchar(100) NOT NULL,
--   date varchar(15) NOT NULL,
--   drawed_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   gift_level int NOT NULL,
--   lottery_name varchar(256) NOT NULL,
--   gift_name varchar(50) NOT NULL,
--   PRIMARY KEY (id)
-- );
--   CREATE INDEX lottery_user_date_idx ON ddl_lottery (user,date);
--   CREATE INDEX lottery_user_idx ON ddl_lottery (user);

-- CREATE TABLE ddl_lottery_delivery (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   user varchar(256) NOT NULL,
--   real_name varchar(50) NOT NULL,
--   user_address clob NOT NULL,
--   phone_number varchar(50) NOT NULL,
--   gift_content clob NOT NULL,
--   PRIMARY KEY (id)
--   CREATE INDEX idx_delivery_user ON  (user(255));
-- );

CREATE TABLE ddl_page_lock (
  rid int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  uid varchar(45) NOT NULL,
  last_access timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  max_version int NOT NULL,
  PRIMARY KEY (rid)
);

CREATE TABLE ddl_space_gained (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  -- COMMENT '创建者'
  uid varchar(45) DEFAULT NULL,
  --  COMMENT '活动等关联的ID'
  obj_id int DEFAULT NULL,
  -- COMMENT '1代表活动'
  obj_type int DEFAULT NULL,
  --  COMMENT '1可分配团队空间 2自动分配的盘空间 '
  space_type int DEFAULT NULL,
  size bigint DEFAULT NULL,
  remark varchar(255) DEFAULT NULL,
  create_time date DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX space_gained_uor ON ddl_space_gained (uid,obj_id,remark);


-- CREATE TABLE dmldata_form (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   formid varchar(255) DEFAULT NULL,
--   dmldesc varchar(255) DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE dmldata_input (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   inputname varchar(255) DEFAULT NULL,
--   inputtype varchar(255) DEFAULT NULL,
--   formid varchar(255) DEFAULT NULL,
--   dmldesc varchar(255) DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

CREATE TABLE pan_share_resource (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  share_uid varchar(45) NOT NULL,
  share_path clob NOT NULL,
  pan_share_id varchar(45) NOT NULL,
  password varchar(10) DEFAULT NULL,
  share_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expire_millis bigint DEFAULT NULL,
  download_count int DEFAULT NULL,
  status varchar(45) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE share_resource (
  rid int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  share_uid varchar(45) NOT NULL,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_editor varchar(45) NOT NULL,
  last_edit_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  password varchar(45) DEFAULT NULL,
  download_count int DEFAULT NULL,
  PRIMARY KEY (rid)
);

-- CREATE TABLE sphinx_counter (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   max_doc_id int NOT NULL,
--   counter int NOT NULL,
--   PRIMARY KEY (id)
-- );

CREATE TABLE vwb_activation (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  email varchar(255) NOT NULL DEFAULT '',
  password varchar(255) NOT NULL DEFAULT '',
  name varchar(255) NOT NULL DEFAULT '',
  encode varchar(255) NOT NULL DEFAULT '',
  status varchar(45) NOT NULL DEFAULT '',
  tname varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

-- CREATE TABLE vwb_app_info (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   context varchar(45) NOT NULL,
--   description clob NOT NULL,
--   issys smallint NOT NULL DEFAULT 0,
--   tid int NOT NULL DEFAULT 0,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_app_map (
--   resourceId int NOT NULL,
--   context varchar(45) NOT NULL,
--   pageId varchar(45) NOT NULL,
--   tid int NOT NULL DEFAULT 0,
--   PRIMARY KEY (resourceId,tid)
-- );

-- CREATE TABLE vwb_banner (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   name varchar(100) DEFAULT NULL,
--   status smallint NOT NULL DEFAULT 0,
--   type int NOT NULL,
--   creator varchar(100) DEFAULT NULL,
--   createdTime timestamp DEFAULT NULL,
--   dirName varchar(100) DEFAULT NULL,
--   leftName varchar(100) DEFAULT NULL,
--   rightName varchar(100) DEFAULT NULL,
--   middleName varchar(100) DEFAULT NULL,
--   pageId int NOT NULL,
--   ownedtype varchar(100) DEFAULT 'system',
--   tid int NOT NULL DEFAULT 0,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_blacklist (
--   page_id int NOT NULL DEFAULT 0,
--   tid int NOT NULL DEFAULT 0,
--   PRIMARY KEY (page_id,tid)
-- );

CREATE TABLE vwb_browse_log (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  user_id varchar(255) NOT NULL DEFAULT '',
  item_id int DEFAULT NULL,
  browse_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  display_name varchar(255) DEFAULT NULL,
  tracking_id varchar(255) DEFAULT NULL,
  item_type varchar(10) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX vwb_browse_log_tracking_id ON vwb_browse_log (tracking_id);

-- CREATE TABLE vwb_clb (
--   RESOURCEID int NOT NULL,
--   CLBID int NOT NULL DEFAULT 0,
--   FILENAME varchar(100) NOT NULL DEFAULT '',
--   SUFFIX varchar(50) DEFAULT NULL,
--   CHANGE_TIME timestamp DEFAULT NULL,
--   LENGTH int DEFAULT NULL,
--   change_by varchar(255) DEFAULT NULL,
--   VERSION int NOT NULL,
--   CHANGE_NOTE varchar(100) DEFAULT NULL,
--   ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int NOT NULL DEFAULT 0,
--   PRIMARY KEY (ID)
--   CREATE INDEX DCT_ATT_CHANGE_TIME_IX ON  (CHANGE_TIME);
-- );

CREATE TABLE vwb_client_invite (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  invitor varchar(255) NOT NULL DEFAULT '',
  invitee varchar(255) NOT NULL DEFAULT '',
  invitetime timestamp DEFAULT NULL,
  accepttime timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX invitee ON vwb_client_invite (invitee);

CREATE TABLE vwb_client_message (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  username varchar(255) NOT NULL DEFAULT '',
  readed smallint NOT NULL DEFAULT 0,
  createtime timestamp DEFAULT NULL,
  readtime timestamp DEFAULT NULL,
  message clob,
  PRIMARY KEY (id)
);
CREATE INDEX vwb_client_message_username ON vwb_client_message (username);

-- CREATE TABLE vwb_collection (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   resource_id int NOT NULL DEFAULT 0,
--   name varchar(255) NOT NULL DEFAULT '',
--   description clob,
--   sequence int DEFAULT NULL,
--   tid int NOT NULL DEFAULT 0,
--   default_auth varchar(45) NOT NULL DEFAULT '',
--   grid_column int DEFAULT NULL,
--   home_mode varchar(45) DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_collection_acl (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int NOT NULL DEFAULT 0,
--   cid varchar(55) NOT NULL DEFAULT 0,
--   uid varchar(55) NOT NULL DEFAULT 0,
--   auth varchar(45) NOT NULL DEFAULT '',
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_collection_element (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int NOT NULL DEFAULT 0,
--   cid int NOT NULL DEFAULT 0,
--   resource_type varchar(45) NOT NULL DEFAULT '',
--   title varchar(255) NOT NULL DEFAULT '',
--   creator varchar(45) NOT NULL DEFAULT '',
--   create_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
--   modifier varchar(45) NOT NULL DEFAULT '',
--   modify_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
--   resource_id int NOT NULL DEFAULT 0,
--   version int NOT NULL DEFAULT 0,
--   PRIMARY KEY (id)
-- );

CREATE TABLE vwb_comment (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  receiver varchar(50) DEFAULT NULL,
  content clob,
  create_time timestamp DEFAULT NULL,
  sender varchar(50) DEFAULT NULL,
  tid int NOT NULL DEFAULT 0,
  rid int NOT NULL,
  item_type varchar(255) DEFAULT NULL,
  status varchar(10) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX comment_index ON vwb_comment (tid,item_type);

CREATE TABLE vwb_dfile (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  owner varchar(100) NOT NULL DEFAULT '',
  cid int NOT NULL DEFAULT 0,
  tid int NOT NULL DEFAULT 0,
  clb_id int NOT NULL DEFAULT 0,
  status varchar(45) DEFAULT 'available',
  PRIMARY KEY (id)
);

CREATE TABLE vwb_dfile_ref (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  page_rid int NOT NULL,
  file_rid int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX file_ref_index ON vwb_dfile_ref (tid);

-- CREATE TABLE vwb_dfile_version (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   fid int NOT NULL DEFAULT 0,
--   version int NOT NULL DEFAULT 0,
--   size int NOT NULL DEFAULT 0,
--   change_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
--   change_by varchar(100) NOT NULL DEFAULT '',
--   title varchar(200) NOT NULL DEFAULT '',
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_dpage_content_info (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int NOT NULL DEFAULT 0,
--   title varchar(255) DEFAULT NULL,
--   resourceid int NOT NULL,
--   version int NOT NULL DEFAULT 1,
--   change_time timestamp DEFAULT NULL,
--   change_note varchar(100) DEFAULT NULL,
--   content clob NOT NULL,
--   change_by varchar(50) NOT NULL,
--   PRIMARY KEY (id)
--   CREATE UNIQUE INDEX dpage_content_info_unique_version ON  (tid,resourceid,version);
-- );

CREATE TABLE vwb_dpage_draft (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  rid int NOT NULL,
  uid varchar(45) NOT NULL DEFAULT '',
  type varchar(45) NOT NULL DEFAULT '',
  content clob,
  modify_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  title clob,
  PRIMARY KEY (id)
);
CREATE INDEX dpage_draft_index ON vwb_dpage_draft (tid,uid);

-- CREATE TABLE vwb_email_notify (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int NOT NULL DEFAULT 0,
--   subscriber varchar(45) NOT NULL,
--   receiver varchar(45) NOT NULL,
--   rec_time varchar(45) NOT NULL,
--   resourceId varchar(255) DEFAULT NULL,
--   page_title varchar(255) DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

CREATE TABLE vwb_event (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  actor varchar(80) NOT NULL,
  operation varchar(80) NOT NULL,
  target varchar(80) NOT NULL,
  target_type varchar(20) NOT NULL,
  target_version int NOT NULL,
  recipients clob,
  message clob,
  occur_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX vwb_event_index ON vwb_event (tid,actor,target);

-- 
-- /*!50001
-- 
-- CREATE TABLE vwb_file_last_version (
--  tid smallint NOT NULL,
--   fid smallint NOT NULL,
--   last_version smallint NOT NULL
-- );

-- CREATE TABLE vwb_grid (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int DEFAULT NULL,
--   cid int DEFAULT NULL,
--   sequence int DEFAULT NULL,
--   title varchar(256) DEFAULT NULL,
--   type varchar(45) DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_grid_item (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int DEFAULT NULL,
--   gid int DEFAULT NULL,
--   resource_type varchar(45) DEFAULT NULL,
--   resource_id int DEFAULT NULL,
--   sequence int DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

CREATE TABLE vwb_invitation (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  encode varchar(255) NOT NULL DEFAULT '',
  inviter varchar(255) NOT NULL DEFAULT '',
  invitee varchar(255) NOT NULL DEFAULT '',
  team int NOT NULL DEFAULT 0,
  accept_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  invite_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  status varchar(45) NOT NULL DEFAULT '',
  message clob,
  PRIMARY KEY (id)
);
CREATE INDEX invitation_index ON vwb_invitation (invitee,team);

CREATE TABLE vwb_message (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  message_id int NOT NULL DEFAULT 0,
  user_id varchar(255) NOT NULL DEFAULT '',
  status int NOT NULL DEFAULT 0,
  publisher int NOT NULL DEFAULT 0,
  publisher_type varchar(255) NOT NULL DEFAULT '',
  tid int NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE vwb_message_body (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  type varchar(45) NOT NULL DEFAULT '',
  title varchar(255) DEFAULT '',
  digest clob,
  time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  "from" varchar(255) NOT NULL DEFAULT '',
  remark clob,
  tid int NOT NULL DEFAULT 0,
  rid int NOT NULL,
  PRIMARY KEY (id)
);

-- CREATE TABLE vwb_myspace (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   eid varchar(50) NOT NULL,
--   resourceId int NOT NULL,
--   name varchar(255) DEFAULT NULL,
--   tid int NOT NULL DEFAULT 0,
--   PRIMARY KEY (id)
-- );

CREATE TABLE vwb_notice (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  event_id int NOT NULL,
  notice_type varchar(45) NOT NULL,
  recipient varchar(255) NOT NULL,
  reason varchar(20) NOT NULL,
  actor_id varchar(80) NOT NULL,
  actor_name varchar(80) NOT NULL,
  actor_url varchar(255) DEFAULT NULL,
  operation varchar(20) NOT NULL,
  target_id varchar(45) NOT NULL,
  target_type varchar(20) NOT NULL,
  target_name varchar(255) DEFAULT NULL,
  target_url varchar(255) DEFAULT NULL,
  target_version int NOT NULL,
  message clob,
  occur_time timestamp NOT NULL DEFAULT '2009-12-31 16:00:00',
  addition clob,
  relative_id varchar(80) DEFAULT NULL,
  relative_name varchar(255) DEFAULT NULL,
  relative_url varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX notice_event_id_index ON vwb_notice (event_id);
CREATE INDEX notice_index ON vwb_notice (tid,notice_type,recipient);
CREATE INDEX target_id_notice_type ON vwb_notice (target_id,notice_type);

CREATE TABLE vwb_oauth_accessor (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  consumer_key varchar(255) NOT NULL DEFAULT '0',
  request_token varchar(255) DEFAULT '',
  token_secret varchar(255) DEFAULT NULL,
  request_create_time timestamp DEFAULT NULL,
  access_token varchar(255) DEFAULT NULL,
  access_create_time timestamp DEFAULT NULL,
  user_id varchar(255) DEFAULT NULL,
  authorized smallint NOT NULL DEFAULT 0,
  screen_name varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
);

CREATE TABLE vwb_oauth_consumer (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  "key" varchar(255) NOT NULL DEFAULT '',
  secret varchar(255) NOT NULL DEFAULT '',
  callback_url varchar(255) DEFAULT NULL,
  enable smallint NOT NULL DEFAULT 1,
  xauth smallint NOT NULL DEFAULT 0,
  description varchar(255) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX vwb_oauth_key ON vwb_oauth_consumer ("key");

CREATE TABLE vwb_person_contacts (
  uid varchar(45) NOT NULL DEFAULT '',
  main_email varchar(45) NOT NULL DEFAULT '',
  option_email varchar(45) DEFAULT '',
  name varchar(45) NOT NULL DEFAULT '',
  orgnization varchar(255) DEFAULT NULL,
  department varchar(255) DEFAULT NULL,
  sex varchar(45) DEFAULT NULL,
  telephone varchar(45) DEFAULT NULL,
  mobile varchar(45) DEFAULT NULL,
  qq varchar(45) DEFAULT NULL,
  msn varchar(45) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  photo varchar(45) DEFAULT NULL,
  birthday varchar(45) DEFAULT NULL,
  weibo varchar(45) DEFAULT NULL,
  pinyin varchar(55) DEFAULT NULL,
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  PRIMARY KEY (id)
);

-- CREATE TABLE vwb_portal_page (
--   resourceId int NOT NULL DEFAULT 0,
--   title varchar(255) DEFAULT NULL,
--   uri varchar(255) DEFAULT NULL,
--   tid int NOT NULL DEFAULT 0,
--   CREATE UNIQUE INDEX index ON  (resourceId,tid);
-- );

-- CREATE TABLE vwb_portal_portlets (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   resourceId int DEFAULT NULL,
--   context varchar(255) DEFAULT NULL,
--   name varchar(255) DEFAULT NULL,
--   tid int NOT NULL DEFAULT 0,
--   PRIMARY KEY (id)
--   CREATE UNIQUE INDEX resourceId ON  (resourceId,tid);
-- );

-- CREATE TABLE vwb_properties (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   strName varchar(255) DEFAULT NULL,
--   strValue varchar(255) DEFAULT NULL,
--   iSiteNum varchar(255) DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_push_message (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   name varchar(50) DEFAULT '',
--   email varchar(100) DEFAULT '',
--   telephone varchar(15) DEFAULT NULL,
--   orgnization varchar(255) DEFAULT NULL,
--   department varchar(255) DEFAULT '',
--   mobile varchar(15) DEFAULT NULL,
--   qq varchar(45) DEFAULT NULL,
--   msn varchar(45) DEFAULT NULL,
--   weibo varchar(45) DEFAULT NULL,
--   sex varchar(2) DEFAULT NULL,
--   address varchar(200) DEFAULT NULL,
--   photo longblob,
--   firstname varchar(255) DEFAULT NULL,
--   lastname varchar(255) DEFAULT NULL,
--   operation int DEFAULT NULL,
--   createdby varchar(100) DEFAULT '',
--   createtime timestamp DEFAULT NULL,
--   modifiedby varchar(100) DEFAULT '',
--   modifytime timestamp DEFAULT NULL,
--   teamid int DEFAULT NULL,
--   issystemuser int DEFAULT NULL,
--   version int DEFAULT NULL,
--   notificationid varchar(100) DEFAULT NULL,
--   status int DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_request_num (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   email varchar(100) NOT NULL,
--   date varchar(50) DEFAULT NULL,
--   count int DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_resource_acl (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   tid int NOT NULL DEFAULT 0,
--   resourceId int NOT NULL,
--   type varchar(10) DEFAULT NULL,
--   eid varchar(50) NOT NULL,
--   action varchar(255) NOT NULL,
--   resourceType varchar(10) NOT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_resource_info (
--   id int NOT NULL DEFAULT 0,
--   tid int NOT NULL DEFAULT 0,
--   type varchar(64) DEFAULT NULL,
--   title varchar(255) DEFAULT NULL,
--   trail int DEFAULT 0,
--   parent int DEFAULT 0,
--   left_menu int DEFAULT 0,
--   top_menu int DEFAULT 0,
--   footer int DEFAULT 0,
--   banner int DEFAULT 0,
--   create_time timestamp DEFAULT NULL,
--   creator varchar(255) DEFAULT NULL,
--   acl int DEFAULT 0,
--   cid int DEFAULT NULL,
--   sphinx_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   last_editor varchar(255) DEFAULT NULL,
--   last_edit_time timestamp DEFAULT NULL,
--   last_version int NOT NULL DEFAULT 1,
--   PRIMARY KEY (sphinx_id),
--   CREATE UNIQUE INDEX id ON  (tid,id);
-- );

CREATE TABLE vwb_share_access (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(50) NOT NULL,
  tid int NOT NULL,
  fid int NOT NULL,
  password varchar(24) NOT NULL,
  create_time timestamp NOT NULL,
  valid_of_days int NOT NULL,
  clb_id int NOT NULL,
  fetch_file_code varchar(20) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX share_access_index ON vwb_share_access (tid,clb_id);

-- CREATE TABLE vwb_share_acl (
--   ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   hash varchar(45) NOT NULL,
--   URL varchar(256) NOT NULL,
--   accessTime bigint NOT NULL,
--   shareTime bigint NOT NULL,
--   PRIMARY KEY (ID)
-- );

-- CREATE TABLE vwb_shortcut (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   title varchar(255) NOT NULL DEFAULT '',
--   resource_id varchar(45) DEFAULT NULL,
--   sequence int NOT NULL DEFAULT 0,
--   collection_id int NOT NULL DEFAULT 0,
--   tid int NOT NULL DEFAULT 0,
--   resource_type varchar(45) DEFAULT 'DPage',
--   PRIMARY KEY (id)
-- );

CREATE TABLE vwb_subscription (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  user_id varchar(255) NOT NULL DEFAULT '',
  publisher int NOT NULL DEFAULT 0,
  publisher_type varchar(45) NOT NULL DEFAULT '',
  policy varchar(45) NOT NULL DEFAULT '',
  tid int NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE INDEX subscription_inde ON vwb_subscription (user_id,tid);

CREATE TABLE vwb_team (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  state varchar(255) DEFAULT NULL,
  prefix varchar(255) DEFAULT NULL,
  create_time timestamp DEFAULT NULL,
  name varchar(255) NOT NULL DEFAULT '',
  display_name varchar(255) NOT NULL DEFAULT '',
  description clob NOT NULL,
  creator varchar(45) NOT NULL DEFAULT '',
  type varchar(45) DEFAULT 'common',
  access_type varchar(20) NOT NULL,
  default_member_auth varchar(20) NOT NULL,
  vmtdn varchar(255) DEFAULT NULL,
  team_default_view varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX vwb_team_index ON vwb_team (name);

CREATE TABLE vwb_team_acl (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  uid varchar(50) NOT NULL DEFAULT '0',
  auth varchar(45) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
);
CREATE INDEX team_acl_index ON vwb_team_acl (tid,uid);

CREATE TABLE vwb_team_applicant (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  uid varchar(45) NOT NULL,
  tid int NOT NULL,
  status varchar(255) NOT NULL,
  reason varchar(255) DEFAULT NULL,
  apply_time timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  i_know varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE vwb_team_create_info (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL,
  param_key varchar(45) NOT NULL,
  param_value varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE vwb_team_member (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  tid int NOT NULL DEFAULT 0,
  uid varchar(45) NOT NULL DEFAULT '',
  title varchar(45) NOT NULL DEFAULT '',
  sequence int DEFAULT -1,
  team_access timestamp NOT NULL DEFAULT '2009-12-31 16:00:00',
  person_access timestamp NOT NULL DEFAULT '2009-12-31 16:00:00',
  monitor_access timestamp NOT NULL DEFAULT '2009-12-31 16:00:00',
  team_notice_count int NOT NULL DEFAULT 0,
  person_notice_count int NOT NULL DEFAULT 0,
  monitor_notice_count int NOT NULL DEFAULT 0,
  team_event_ids clob,
  person_event_ids clob,
  monitor_event_ids clob,
  createdby varchar(50) DEFAULT NULL,
  createtime timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX team_member_index ON vwb_team_member (tid,uid);
CREATE INDEX team_member_uid_index ON vwb_team_member (uid);

-- CREATE TABLE vwb_team_relations (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   allUserId varchar(100) DEFAULT '',
--   systemUserId varchar(100) DEFAULT '',
--   count int DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

CREATE TABLE vwb_user_ext (
  uid varchar(45) NOT NULL DEFAULT '',
  name varchar(45) NOT NULL DEFAULT '',
  email varchar(45) DEFAULT NULL,
  orgnization varchar(255) DEFAULT NULL,
  department varchar(255) DEFAULT NULL,
  sex varchar(45) DEFAULT NULL,
  telephone varchar(45) DEFAULT NULL,
  mobile varchar(45) DEFAULT NULL,
  qq varchar(45) DEFAULT NULL,
  msn varchar(45) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  photo varchar(45) DEFAULT NULL,
  birthday varchar(45) DEFAULT NULL,
  weibo varchar(255) DEFAULT NULL,
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  pinyin varchar(255) DEFAULT NULL,
  regist_time timestamp DEFAULT NULL,
  frequent int DEFAULT NULL,
  operation int DEFAULT NULL,
  requestNum int DEFAULT NULL,
  version int DEFAULT NULL,
  modifytime timestamp DEFAULT NULL,
  confirm_status varchar(15) DEFAULT NULL,
  --  COMMENT '未分配的空间'
  unallocated_space bigint DEFAULT 0,
  PRIMARY KEY (id,uid)
);
CREATE INDEX pinyin_tree_index ON vwb_user_ext (pinyin);
-- CREATE INDEX uid_tree_index ON vwb_user_ext (uid(10)) USING BTREE;
CREATE INDEX vwb_user_ext_uid_index ON vwb_user_ext (uid);

CREATE TABLE vwb_user_feedback (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
  email varchar(50) NOT NULL,
  message clob NOT NULL,
  send_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status varchar(20) NOT NULL,
  PRIMARY KEY (id)
);

-- CREATE TABLE vwb_user_history (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   name varchar(50) DEFAULT '',
--   email varchar(100) DEFAULT '',
--   telephone varchar(15) DEFAULT NULL,
--   orgnization varchar(255) DEFAULT NULL,
--   department varchar(255) DEFAULT '',
--   mobile varchar(15) DEFAULT NULL,
--   sex varchar(2) DEFAULT NULL,
--   qq varchar(45) DEFAULT NULL,
--   msn varchar(45) DEFAULT NULL,
--   weibo varchar(45) DEFAULT NULL,
--   address varchar(200) DEFAULT NULL,
--   photo longblob,
--   firstname varchar(255) DEFAULT NULL,
--   lastname varchar(255) DEFAULT NULL,
--   operation int DEFAULT NULL,
--   createdby varchar(100) DEFAULT '',
--   createtime timestamp DEFAULT NULL,
--   modifiedby varchar(100) DEFAULT '',
--   modifytime timestamp DEFAULT NULL,
--   version int DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_user_outside (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   name varchar(50) DEFAULT '',
--   email varchar(100) DEFAULT '',
--   telephone varchar(15) DEFAULT NULL,
--   orgnization varchar(255) DEFAULT NULL,
--   department varchar(255) DEFAULT '',
--   mobile varchar(15) DEFAULT NULL,
--   qq varchar(45) DEFAULT NULL,
--   msn varchar(45) DEFAULT NULL,
--   weibo varchar(45) DEFAULT NULL,
--   sex varchar(45) DEFAULT NULL,
--   address varchar(200) DEFAULT NULL,
--   photo longblob,
--   firstname varchar(255) DEFAULT NULL,
--   lastname varchar(255) DEFAULT NULL,
--   operation int DEFAULT NULL,
--   createdby varchar(100) DEFAULT '',
--   createtime timestamp DEFAULT NULL,
--   modifiedby varchar(100) DEFAULT '',
--   modifytime timestamp DEFAULT NULL,
--   version int DEFAULT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE vwb_user_to_be_processed (
--   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 64),
--   name varchar(50) DEFAULT '',
--   email varchar(100) DEFAULT '',
--   telephone varchar(15) DEFAULT NULL,
--   orgnization varchar(255) DEFAULT '',
--   department varchar(255) DEFAULT '',
--   mobile varchar(15) DEFAULT NULL,
--   sex varchar(2) DEFAULT NULL,
--   qq varchar(45) DEFAULT NULL,
--   msn varchar(45) DEFAULT NULL,
--   weibo varchar(45) DEFAULT NULL,
--   address varchar(200) DEFAULT NULL,
--   photo longblob,
--   firstname varchar(255) DEFAULT NULL,
--   lastname varchar(255) DEFAULT NULL,
--   operation int DEFAULT NULL,
--   createdby varchar(100) DEFAULT '',
--   createtime timestamp DEFAULT NULL,
--   modifiedby varchar(100) DEFAULT '',
--   modifytime timestamp DEFAULT NULL,
--   version int DEFAULT NULL,
--   issystemuser int DEFAULT NULL,
--   teamid int DEFAULT NULL,
--   result varchar(255) DEFAULT '',
--   PRIMARY KEY (id)
-- );


-- /*!50001 VIEW vwb_file_last_version AS select f.tid AS tid,v.fid AS fid,max(v.version) AS last_version from (vwb_dfile f join vwb_dfile_version v) where (v.fid = f.id) group by v.fid */;

-- Dump completed on 2016-06-04 23:39:05
